#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar height=37             \
                 blur_radius=40        \
                 position=top          \
                 sticky=on             \
                 topmost=window        \
                 show_in_fullscreen=on \
                 padding_left=10       \
                 padding_right=10      \
                 color=$BAR_COLOR

##### Changing Defaults #####
sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$WHITE                 \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$WHITE                \
                     background.drawing=off                \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \
                     icon.padding_right=4

# Custom event fired by AeroSpace's exec-on-workspace-change (see ~/.aerospace.toml)
sketchybar --add event aerospace_workspace_change

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
sketchybar --add item right_separator right \
           --set right_separator icon="􀆊"                \
                                 icon.color=$ACCENT_COLOR \
                                 icon.padding_left=4      \
                                 icon.padding_right=4     \
                                 label.drawing=off        \
                                 background.drawing=off

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/meeting.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/cpu.sh

##### Finalizing Setup #####
sketchybar --update
